### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by maphew** [jachetto/alp2gpx#6]
Hi, I'm brand new to this project. Below is the traceback I get when trying to naively\* run alp2gpx on my exported AQ data of last couple of months, about 1.6mb. I have a bit of python skill and will attempt to diagnose and solve the problem myself if I can, i.e. this isn't a call of "heeeeelllp!", unless of course you know the answer already. ;-) I'll treat this opening post as wiki and edit/refine as I learn my through this new landscape. 

_\*I haven't looked at the code at all yet. I'm travelling for next 3 days and might not get back to this until after.__

```
» python alp2gpx.py data\matt-in.ldk
Traceback (most recent call last):
  File "C:\Users\Matt\code\alp2gpx\alp2gpx.py", line 599, in <module>
    q = alp2gpx(args.input, args.output)
  File "C:\Users\Matt\code\alp2gpx\alp2gpx.py", line 44, in __init__
    self.parse_ldk()
  File "C:\Users\Matt\code\alp2gpx\alp2gpx.py", line 582, in parse_ldk
    root_node = self._get_node(position_of_the_root_node)
  File "C:\Users\Matt\code\alp2gpx\alp2gpx.py", line 309, in _get_node
    child = self._get_node(entry['offset'], path, entry['uuid']);
  File "C:\Users\Matt\code\alp2gpx\alp2gpx.py", line 313, in _get_node
    data = self._get_node_data(entry)
  File "C:\Users\Matt\code\alp2gpx\alp2gpx.py", line 245, in _get_node_data
    data += self._get_raw(size)
TypeError: can only concatenate str (not "bytes") to str
```

Relevant environment info:
```
     active environment : alp2gpx
    active env location : C:\Users\Matt\.conda\envs\alp2gpx
            shell level : 1
          conda version : 4.12.0
         python version : 3.9.5.final.0
       base environment : C:\ProgramData\scoop\apps\miniconda3\current  (read only)
               platform : win-64
             user-agent : conda/4.12.0 requests/2.25.1 CPython/3.9.5 Windows/10 Windows/10.0.19044
```

Alpine Quest 2.3.2c on Android 12 (Pixel Pro).

**Comment by jachetto** [comment]
tnx for your report. The question here is that alp2gpx has really poor support for ldk or better has no support, just a method placeholder into the code. I've modified the README in order to not lead confusion.
Teoritically LDK are not so different from TRK, they are just a container of TRK , but everything should be deeply investigated.
Here a list of useful resources

- https://psyberia.net/res/specs/psyberia_landmarks_files_specs.pdf
- https://psyberia.net/res/specs/psyberia_archive_file_specs.pdf
- https://www.alpinequest.net/en/help/v2/landmarks
- https://www.alpinequest.net/forum/viewtopic.php?f=3&t=3319
- https://www.alpinequest.net/forum/viewtopic.php?f=4&t=5045

**Comment by maphew** [comment]
Thank you for the resources! 

I'm slowly slowly picking my way through. If you care to watch see https://github.com/jachetto/alp2gpx/compare/master...maphew:alp2gpx:master. Next step is to build some simpler and shareable test data.

The filetype numbers I'm getting are very different from the ones noted in the code (Line ~320). "189812838, 240144488, 173035621" vs "101, 102, 103, ...".  Did you get yours from trial and error or from the Psyberia docs or forum somewhere?

**Comment by jachetto** [comment]
you can give an eye to https://psyberia.net/res/specs/psyberia_landmarks_files_specs.pdf point 1.1 to 1.6
Type not listed from 101...104 are marked as 'primitives'.
Don't ask me what they mean by 'primitives' :)

**Comment by flavienbwk** [comment]
Hi is there any update on supporting LDK file format ? Thanks

**Comment by jachetto** [comment]
Nope. There Is no plan atm for ldk support
